name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - prod

  push:
    branches:
      - main
      - prod

permissions:
  contents: read

env:
  CIVO_TOKEN: ${{ secrets.CIVO_TOKEN }}
  AWS_REQUEST_CHECKSUM_CALCULATION: when_required
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Show GitHub Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref_name }}"
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Select Terraform Workspace
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ github.head_ref }}" = "prod" ]; then
              WORKSPACE="prod"
            else
              WORKSPACE="dev"
            fi
          else
            if [ "${{ github.ref_name }}" = "prod" ]; then
              WORKSPACE="prod"
            else
              WORKSPACE="dev"
            fi
          fi

          echo "Selected Terraform workspace: $WORKSPACE"

          terraform workspace select -or-create "$WORKSPACE"

          echo "Current Terraform workspace:"
          terraform workspace show

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_region: ${{ vars.TF_VAR_region }}
          TF_VAR_disk_image: ${{ vars.disk_image }}
          TF_VAR_ssh_key_id: ${{ vars.ssh_key_id }}
        run: terraform plan -lock-timeout=5m
